spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
  application:
    name: configuration

server:
  port: 8888
